version: '3.8'
services:
  streamlit-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-chat-ui
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://34.14.209.200:8000
    restart: unless-stopped
